feature(integration): integrate questionService with question SPA
CS3219-AY2324S1/ay2324s1-assignment-6-g38 pull request #15
Opened 2023-10-14 12:11 UTC by fullfatwasabi

### Add integration from question page to question-service
1.  Adding Questions
2.  Fetching Questions
3.  Deleting Questions

(Will perhaps add 'Edit' in a separate PR but not sure if it's a necessity for now 🤔)

## Changelog:
1. Changed baseUrl of rootApi to http:// so our .env file would have the localhost:xxxx path for each micro-service
```
NEXT_PUBLIC_QUESTION_SERVICE_ADDRESS=localhost:2001
NEXT_PUBLIC_USER_SERVICE_ADDRESS=localhost:5001
```

2. Moved checks on duplicate questions to question-service, but I'm not sure how to handle the typing for the errors on the frontend. e.g. the last 4 lines:
 ```
addQuestion(newQuestion)
    .unwrap()
    .then((returnedQuestion: QuestionType) => {
      setQuestions((prevQuestions) => [...prevQuestions, returnedQuestion]);
    })
    .catch((err) => {
      // eslint-disable-next-line no-alert
      alert(
        err.data.error[0].message ??
          err.data.error ??
          "An error occurred. Please refresh and try again later",
      );
    });
```
Do feel free to leave your thoughts/suggestions on these two changes! 🍰

2023-10-14 15:03 UTC, sbhbenjamin requested changes
Thanks for integrating the questions service to the frontend! Overall, great job on handling all of the different api states i.e. `loading`, `success` and `error`. 

The main comments I have are regarding the way mutation and query hooks are used in components, the core principles of RTK query allows to [write code without having to deal with Promises (i.e. promise chaining, inability to write asynchronous code in a synchronous pattern](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics), and I think that is quite a good pattern to follow. Open to discussion on your thoughts on this!

2023-10-14 15:03 UTC, sbhbenjamin commented on frontend/src/app/questions/page.tsx
>    const [questions, setQuestions] = useState<QuestionType[]>([]);
I think this should be removed, we can just use the data state from `useGetQuestionsQuery` instead of creating a new state and setting it in a `useEffect` hook!

2023-10-14 15:03 UTC, sbhbenjamin commented on frontend/src/app/questions/page.tsx
> +      });
For `addQuestion` and `deleteQuestion`, we dont have to handle all of these conditions because RTK query provides the loading, success and error states when we use the action. It allows us to avoid having to handle promises this way, and write code more synchronously! The [RTK Query documentation](https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics) is quite a good resource on this!

```
// when using the question hook
const {deleteQuestion, { isLoading, isSuccess: isDeleteSuccess, isError: isDeleteError }} = useDeleteQuestionMutation()
```
I have also created a notification hook that you can use, you just need to pass in the api states i.e. `isSuccess`, `isError`, and when the booleans are `true`, the notification will be dispatched and rendered on the screen.
```
 useApiNotifications({
    isSuccess: isDeleteSuccess,
    isError: isDeleteError,
    successMessage: "Successfully deleted question!",
  });
```

For an example that uses this pattern, you can take a look at `EditProfileForm.tsx`!

2023-10-14 15:03 UTC, sbhbenjamin commented on frontend/src/features/questions/components/QuestionForm.tsx
> +    if (addQuestionResults.status === QueryStatus.fulfilled) {
I think if you get the `isSuccess` state from `useAddQuestionMutation`, you can just do
```
if (isSuccess) {
    form.reset()
} 
```

2023-10-14 15:03 UTC, sbhbenjamin commented on frontend/src/features/questions/components/QuestionForm.tsx
> +            addQuestionResults.status === QueryStatus.pending
Similarly, instead of having to check the status of addQuestionResults, you can use the attribute exposed `isLoading`

2023-10-14 15:39 UTC, aweijun reviewed
Great work sir!

2023-10-14 15:39 UTC, aweijun commented on frontend/src/app/questions/page.tsx
> +  }, [data]);
Is this useEffect neccessary?

2023-10-14 15:39 UTC, aweijun commented on frontend/src/app/questions/page.tsx
> +        );
Actually, you can use the notification hook that **BEN** wrote recently!

2023-10-14 15:39 UTC, aweijun commented on frontend/src/features/questions/components/QuestionForm.tsx
> +            !form.formState.isValid ||
I think @sbhbenjamin added a loading state for the button

2023-10-14 15:39 UTC, aweijun commented on frontend/src/services/questionApi.ts
> +    getQuestions: builder.query<QuestionType[], Partial<QuestionType> | void>({
I realized there is a better way to handle this recently! I will update you on it.

2023-10-18 16:02 UTC, sbhbenjamin approved these changes
LGTM! Thanks for the changes sir 🫡

2023-10-19 17:06 UTC, merged